tap "buo/cask-upgrade"
tap "felixkratz/formulae", "https://github.com/FelixKratz/homebrew-formulae"
tap "koekeishiya/formulae"
tap "nikitabobko/tap"
tap "shinokawa/nipaplay-reload", "https://github.com/Shinokawa/homebrew-nipaplay-reload"
tap "sst/tap"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Resource monitor. C++ version and continuation of bashtop and bpytop
brew "btop"
# Diff that understands syntax
brew "difftastic"
# Modern, maintained replacement for ls
brew "eza"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Command-line fuzzy finder written in Go
brew "fzf"
# Distributed revision control system
brew "git"
# GNU Privacy Guard (OpenPGP)
brew "gnupg"
# Tools and libraries to manipulate images in select formats
brew "imagemagick"
# Simple terminal UI for git commands
brew "lazygit"
# Interpreted, interactive, object-oriented programming language
brew "python@3.14"
# Mac App Store command-line interface
brew "mas"
# Deep clean and optimize your Mac
brew "mole"
# Incremental parsing library
brew "tree-sitter"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim", args: ["HEAD"]
# Open-source, cross-platform JavaScript runtime environment
brew "node"
# PDF rendering library (based on the xpdf-3.0 code base)
brew "poppler"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# 7-Zip is a file archiver with a high compression ratio
brew "sevenzip"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Very fast implementation of tldr in Rust
brew "tealdeer"
# Programmatically correct mistyped console commands
brew "thefuck"
# Terminal multiplexer
brew "tmux", args: ["HEAD"]
# Blazing fast terminal file manager written in Rust, based on async I/O
brew "yazi", args: ["HEAD"]
# Shell extension to navigate your filesystem faster
brew "zoxide"
# A window border system for macOS
brew "felixkratz/formulae/borders"
# The AI coding agent built for the terminal.
brew "sst/tap/opencode"
# AeroSpace is an i3-like tiling window manager for macOS
cask "nikitabobko/tap/aerospace"
# Application launcher and productivity software
cask "alfred"
# Tool to flash OS images to SD cards & USB drives
cask "balenaetcher"
# Voice and text chat software
cask "discord"
# Web browser
cask "firefox"
cask "font-maple-mono-cn"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Java IDE by JetBrains
cask "intellij-idea"
# Provides updates to various Microsoft products
cask "microsoft-auto-update"
# Spreadsheet software
cask "microsoft-excel"
# OpenJDK distribution from Microsoft
cask "microsoft-openjdk"
# Presentation software
cask "microsoft-powerpoint"
# Word processor
cask "microsoft-word"
# Media player
cask "movist-pro"
cask "shinokawa/nipaplay-reload/nipaplay-reload"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Home media player
cask "plex"
# Instant messaging tool
cask "qq"
# Mesh VPN based on WireGuard
cask "tailscale-app"
# Messaging app with a focus on speed and security
cask "telegram"
# Unpacks archive files
cask "the-unarchiver"
# VPN and WiFi proxy
cask "thunder"
# AI image upscaler
cask "upscayl"
# Free messaging and calling application
cask "wechat"
# Native desktop client for WhatsApp
cask "whatsapp"
mas "GIPHY CAPTURE", id: 668208984
mas "Infuse", id: 1136220934
