if vim.g.colors_name then vim.cmd('hi clear') end
vim.o.termguicolors = true
vim.g.colors_name = 'kuro' -- name used by :colorscheme -- kuro means black

local c = require('palette').kuro

local hl = {
    -- :h highlight-default
    ColorColumn = { link = 'CursorLine' },
    Conceal = { link = 'Nontext' },
    CurSearch = { bg = c.yellow, fg = c.bg },
    Cursor = { bg = c.yellow, fg = c.bg },
    lCursor = { link = 'Cursor' },
    CursorColumn = { link = 'CursorLine' },
    CursorLine = { bg = c.cursorline },
    Directory = { fg = c.magenta, bold = true },
    DiffAdd = { bg = c.green_diff },
    DiffChange = { bg = c.orange_diff },
    DiffDelete = { fg = c.fg_20, bg = c.red_diff },
    DiffText = { fg = c.orange, bg = c.orange_diff, bold = true },
    DiffTextAdd = { fg = c.green, bg = c.orange_diff, bold = true },
    TermCursor = { link = 'Cursor' },
    OkMsg = { fg = c.green },
    WarningMsg = { fg = c.yellow },
    ErrorMsg = { fg = c.red },
    StderrMsg = { link = 'ErrorMsg' },
    StdoutMsg = { fg = c.fg_65 },
    WinSeparator = { fg = c.fg_20 },
    Folded = { fg = c.fg_40, bg = c.bg },
    SignColumn = { bg = c.bg },
    LineNr = { fg = c.fg_40 },
    CursorLineNr = { fg = c.yellow, bold = true },
    MatchParen = { fg = c.yellow, bold = true },
    ModeMsg = { fg = c.green },
    MsgSeparator = { link = 'WinSeparator' },
    MoreMsg = { fg = c.blue },
    NonText = { fg = c.fg_20 },
    Normal = { fg = c.fg_80, bg = c.bg },
    NormalFloat = { fg = c.fg_80, bg = c.backdrop },
    FloatBorder = { fg = c.fg_20, bg = c.backdrop },
    FloatShadow = { bg = c.black },
    FloatShadowThrough = { bg = c.black },
    NormalNC = { fg = c.fg_65, bg = c.bg },
    Pmenu = { bg = c.backdrop },
    PmenuSel = { fg = c.bg, bg = c.green },
    PmenuThumb = { link = 'Visual' },
    ComplMatchIns = { link = 'PreInsert' },
    PreInsert = { fg = c.yellow, bold = true },
    ComplHint = { link = 'Comment' },
    Question = { fg = c.orange, bold = true },
    QuickFixLine = { link = 'Visual' },
    Search = { fg = c.yellow, bold = true },
    SpellBad = { sp = c.red, undercurl = true },
    SpellCap = { sp = c.yellow, undercurl = true },
    SpellLocal = { sp = c.green, undercurl = true },
    SpellRare = { sp = c.cyan, undercurl = true },
    StatusLine = { bg = c.bg },
    StatusLineNC = { bg = c.bg },
    TabLineSel = { fg = c.bg, bg = c.green },
    Title = { fg = c.magenta, bold = true },
    Visual = { bg = c.visual },
    WinBar = { bg = c.bg },
    WinBarNC = { bg = c.bg },

    -- :h group-name
    Comment = { fg = c.fg_40 },
    Constant = { fg = c.fg_95, bold = true },
    String = { fg = c.green },
    Number = { fg = c.orange },
    Boolean = { fg = c.orange },
    Identifier = { fg = c.fg_80 },
    Function = { fg = c.red, bold = true },
    Statement = { fg = c.fg_65, bold = true },
    Operator = { fg = c.fg_40 },
    PreProc = { fg = c.orange, bold = true },
    Type = { fg = c.fg_95, bold = true },
    Special = { fg = c.fg_80, bold = true },
    Tag = { fg = c.orange, bold = true },
    Delimiter = { fg = c.fg_40 },
    Error = { fg = c.bg, bg = c.red },
    Todo = { fg = c.orange },
    Added = { fg = c.green },
    Changed = { fg = c.orange },
    Removed = { fg = c.red },

    -- :h diagnostic-highlights
    DiagnosticError = { fg = c.red },
    DiagnosticWarn = { fg = c.yellow },
    DiagnosticInfo = { fg = c.blue },
    DiagnosticHint = { fg = c.cyan },
    DiagnosticOk = { fg = c.green },
    DiagnosticUnderlineError = { sp = c.red, underline = true },
    DiagnosticUnderlineWarn = { sp = c.yellow, underline = true },
    DiagnosticUnderlineInfo = { sp = c.blue, underline = true },
    DiagnosticUnderlineHint = { sp = c.cyan, underline = true },
    DiagnosticUnderlineOk = { sp = c.green, underline = true },
    DiagnosticDeprecated = { sp = c.fg_40, strikethrough = true },

    -- :h treesitter-highlight-groups
    ['@variable'] = { fg = c.fg_80 },
    ['@keyword.return'] = { fg = c.red, bold = true, italic = true },
    ['@attribute.builtin'] = { link = '@attribute' },
    ['@function.builtin'] = { link = '@function' },
    ['@markup.heading.1'] = { fg = c.magenta, bold = true },
    ['@markup.heading.2'] = { fg = c.blue, bold = true },
    ['@markup.heading.3'] = { fg = c.yellow, bold = true },
    ['@markup.heading.4'] = { fg = c.green, bold = true },
    ['@markup.heading.5'] = { fg = c.orange, bold = true },
    ['@markup.heading.6'] = { fg = c.fg_40, bold = true },
    ['@markup.quote'] = { fg = c.cyan, bold = true },
    ['@markup.math'] = { fg = c.blue, bold = true },
    ['@markup.link'] = { fg = c.blue, bold = true },
    ['@markup.raw'] = { fg = c.red, bold = true },
    ['@markup.raw.block'] = { bg = c.backdrop },
    ['@markup.list.checked'] = { fg = c.green, strikethrough = true },
    ['@markup.list.unchecked'] = { fg = c.fg_40 },
    ['@tag.builtin'] = { link = 'Tag' },

    -- language specific
    ['@constructor.lua'] = { link = '@punctuation.bracket' },

    -- lsp
    ['@lsp.type.variable'] = vim.empty_dict(),

    -- render-markdown
    RenderMarkdownH1Bg = { link = '@markup.heading.1' },
    RenderMarkdownH2Bg = { link = '@markup.heading.2' },
    RenderMarkdownH3Bg = { link = '@markup.heading.3' },
    RenderMarkdownH4Bg = { link = '@markup.heading.4' },
    RenderMarkdownH5Bg = { link = '@markup.heading.5' },
    RenderMarkdownH6Bg = { link = '@markup.heading.6' },
    RenderMarkdownCode = { bg = c.backdrop },
    RenderMarkdownCodeInline = { fg = c.red, bold = true },

    -- fzf-lua
    FzfLuaNormal = { link = 'NormalFloat' },
    FzfLuaBorder = { link = 'FloatBorder' },
    FzfLuaTitle = { link = 'FloatTitle' },

    -- blink
    BlinkCmpMenuSelection = { link = 'PmenuSel' },
    BlinkCmpMenuBorder = { link = 'FloatBorder' },
    BlinkCmpDocBorder = { link = 'FloatBorder' },
    BlinkCmpSignatureHelpBorder = { link = 'FloatBorder' },
    BlinkCmpLabelDeprecated = { fg = c.fg_20, strikethrough = true },
    BlinkCmpSource = { fg = c.cyan },
    BlinkCmpKindText = { link = 'Normal' },
    BlinkCmpKindMethod = { link = '@function.method' },
    BlinkCmpKindFunction = { link = '@function' },
    BlinkCmpKindConstructor = { link = '@constructor' },
    BlinkCmpKindField = { link = '@variable.member' },
    BlinkCmpKindVariable = { link = '@variable' },
    BlinkCmpKindClass = { link = '@type' },
    BlinkCmpKindInterface = { link = '@type' },
    BlinkCmpKindModule = { link = '@module' },
    BlinkCmpKindProperty = { link = '@property' },
    BlinkCmpKindUnit = { link = '@keyword' },
    BlinkCmpKindValue = { link = '@constant' },
    BlinkCmpKindEnum = { link = '@constant' },
    BlinkCmpKindKeyword = { link = '@keyword' },
    BlinkCmpKindSnippet = { link = '@constant' },
    BlinkCmpKindColor = { fg = c.red },
    BlinkCmpKindFile = { link = '@markup.link' },
    BlinkCmpKindReference = { link = '@markup.raw' },
    BlinkCmpKindFolder = { link = 'Title' },
    BlinkCmpKindEnumMember = { link = '@keyword.directive' },
    BlinkCmpKindConstant = { link = '@constant' },
    BlinkCmpKindStruct = { link = 'Structure' },
    BlinkCmpKindEvent = { link = '@character' },
    BlinkCmpKindOperator = { link = '@operator' },
    BlinkCmpKindTypeParameter = { link = '@variable' },

    -- navic
    NavicIconsFile = { link = '@markup.link' },
    NavicIconsModule = { link = '@module' },
    NavicIconsNamespace = { link = '@type' },
    NavicIconsPackage = { link = '@keyword.import' },
    NavicIconsClass = { link = '@type' },
    NavicIconsMethod = { link = '@function.method' },
    NavicIconsProperty = { link = '@property' },
    NavicIconsField = { link = '@variable.member' },
    NavicIconsConstructor = { link = '@constructor' },
    NavicIconsEnum = { link = '@constant' },
    NavicIconsInterface = { link = '@type' },
    NavicIconsFunction = { link = '@function' },
    NavicIconsVariable = { link = '@variable' },
    NavicIconsConstant = { link = '@constant' },
    NavicIconsString = { link = '@string' },
    NavicIconsNumber = { link = '@number' },
    NavicIconsBoolean = { link = '@boolean' },
    NavicIconsArray = { link = 'Delimiter' },
    NavicIconsObject = { link = '@type' },
    NavicIconsKey = { link = '@property' },
    NavicIconsNull = { link = '@constant' },
    NavicIconsEnumMember = { link = '@keyword.directive' },
    NavicIconsStruct = { link = 'Structure' },
    NavicIconsEvent = { link = '@character' },
    NavicIconsOperator = { link = '@operator' },
    NavicIconsTypeParameter = { link = '@variable' },
    NavicText = { link = 'Normal' },
    NavicSeparator = { link = 'Delimiter' },
}

for group, spec in pairs(hl) do
    vim.api.nvim_set_hl(0, group, spec)
end
